# Generated by Django 5.1.4 on 2024-12-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descoint',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
