# Generated by Django 4.2.8 on 2024-12-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
    ]
